//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatHang_ChiTiet
    {
        [Display(Name = "Mã chi tiết")]
        public int ID { get; set; }

        [Display(Name = "Số điện thoại đặt hàng")]
        [Required(ErrorMessage = "Chưa chọn đơn đặt hàng!")]
        public Nullable<int> DatHang_ID { get; set; }

        [Display(Name = "Sách")]
        [Required(ErrorMessage = "Chưa chọn sách!")]
        public Nullable<int> Sach_ID { get; set; }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Số lượng không được bỏ trống!")]
        public Nullable<short> SoLuong { get; set; }

        [Display(Name = "Đơn giá")]
        [Required(ErrorMessage = "Đơn giá không được bỏ trống!")]
        public Nullable<int> DonGia { get; set; }

        public virtual DatHang DatHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}

